language: ruby
rvm:
 - 2.3.3
 - 2.2
node_js: 6
before_install:
    - bash ./scripts/nvm.sh
    - npm install -g surge
    - npm install -g firebase-tools
script:
    - ./scripts/cibuild.sh
after_success:
    - ./scripts/deploy.sh
branches:
    except:
        - gh-pages